const Ascii = require('./ascii');

let i = 0;

const char = desc => {
  return new Ascii(i, String.fromCharCode(i++), desc);
};

const AsciiTable = [
  char('null character'),
  char('start of header'),
  char('start of text'),
  char('end of text'),
  char('end of transmission'),
  char('enquiry'),
  char('acknowledge'),
  char('bell (ring)'),
  char('backspace'),
  char('horizontal tab'),
  char('line feed'),
  char('vertical tab'),
  char('form feed'),
  char('carriage return'),
  char('shift out'),
  char('shift in'),
  char('data link escape'),
  char('device control 1'),
  char('device control 2'),
  char('device control 3'),
  char('device control 4'),
  char('negative acknowledge'),
  char('synchronize'),
  char('end transmission block'),
  char('cancel'),
  char('end of medium'),
  char('substitute'),
  char('escape'),
  char('file separator'),
  char('group separator'),
  char('record separator'),
  char('unit separator'),
  char('space'),
  char('exclamation mark'),
  char('quotation mark'),
  char('number sign'),
  char('dollar sign'),
  char('percent sign'),
  char('ampersand'),
  char('apostrophe'),
  char('left parenthesis'),
  char('right parenthesis'),
  char('asterisk'),
  char('plus sign'),
  char('comma'),
  char('hyphen'),
  char('period'),
  char('slash'),
  char('digit 0'),
  char('digit 1'),
  char('digit 2'),
  char('digit 3'),
  char('digit 4'),
  char('digit 5'),
  char('digit 6'),
  char('digit 7'),
  char('digit 8'),
  char('digit 9'),
  char('colon'),
  char('semicolon'),
  char('less than'),
  char('equals to'),
  char('greater than'),
  char('question mark'),
  char('at sign'),
  char('uppercase A'),
  char('uppercase B'),
  char('uppercase C'),
  char('uppercase D'),
  char('uppercase E'),
  char('uppercase F'),
  char('uppercase G'),
  char('uppercase H'),
  char('uppercase I'),
  char('uppercase J'),
  char('uppercase K'),
  char('uppercase L'),
  char('uppercase M'),
  char('uppercase N'),
  char('uppercase O'),
  char('uppercase P'),
  char('uppercase Q'),
  char('uppercase R'),
  char('uppercase S'),
  char('uppercase T'),
  char('uppercase U'),
  char('uppercase V'),
  char('uppercase W'),
  char('uppercase X'),
  char('uppercase Y'),
  char('uppercase Z'),
  char('left square bracket'),
  char('backslash'),
  char('right square bracket'),
  char('caret'),
  char('underscore'),
  char('backtick'),
  char('lowercase a'),
  char('lowercase b'),
  char('lowercase c'),
  char('lowercase d'),
  char('lowercase e'),
  char('lowercase f'),
  char('lowercase g'),
  char('lowercase h'),
  char('lowercase i'),
  char('lowercase j'),
  char('lowercase k'),
  char('lowercase l'),
  char('lowercase m'),
  char('lowercase n'),
  char('lowercase o'),
  char('lowercase p'),
  char('lowercase q'),
  char('lowercase r'),
  char('lowercase s'),
  char('lowercase t'),
  char('lowercase u'),
  char('lowercase v'),
  char('lowercase w'),
  char('lowercase x'),
  char('lowercase y'),
  char('lowercase z'),
  char('left curly brace'),
  char('vertical bar'),
  char('right curly brace'),
  char('tilde'),
  char('delete (rubout)'),
];

module.exports = AsciiTable;
